### ISSUE TITLE
Failed to load snippets from '.../.atom/packages/atom-jasmine/snippets/blocks.cson'

### ISSUE THREAD

**Issue by dsandstrom** [zacharytamas/atom-jasmine#20]
You have a duplicate key in your snippets, it's causing problems in Atom 1.25.  https://github.com/zacharytamas/atom-jasmine/blob/master/snippets/blocks.cson#L96

**Comment by KMedinaTheDev** [comment]
Hey I was running into the same warning on atom, it was causing the tests not to run in atom which was frustrating, but the following solved the problem (warning went away and tests are running accordingly again :) 

**Solution:**  Remove the pathway by running _rm .../.atom/packages/atom-jasmine/snippets/blocks.cson_ in your terminal, restart atom and the warning should no longer appear and tests will run normally 😃

**Comment by redoper1** [comment]
It's already fixed in the repository, but we need to wait until @zacharytamas will make a new release to be able to update this package in Atom.

Now you can only solve it by fixing the duplicated key locally.

**Comment by zacharytamas** [comment]
Got the new release with the fix out just now! Sorry for the delay, I thought I'd already done this but it turns out that there are a lot of little things that have to be just right for APM to notice and pick up a new version. I had missed one of them. 🤦🏻‍♂️
